name: flutter_quick_video_encoder
description: Quickly encode raw RGB images & PCM audio to mp4 video using the system h264 encoder
version: 1.2.0
homepage: https://github.com/chipweinberger/flutter_quick_video_encoder

environment:
  sdk: ">=2.15.1 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.lib.flutter_quick_video_encoder
        pluginClass: FlutterQuickVideoEncoderPlugin
      ios:
        pluginClass: FlutterQuickVideoEncoderPlugin
      macos:
        pluginClass: FlutterQuickVideoEncoderPlugin

